### ISSUE TITLE
Server don't start!! URGENT!

### ISSUE THREAD

**Issue by ghost** [fengberd/MinecraftPEServer#61] opened 2017-07-04 19:27 UTC
Tesseract > 
┌─────────────────────────────────────────────────┐  -- Loaded: Properties and Configuration --
│                                                 │    Date: Wed, July 05, 2017, 03:18 CST
│   _______                                _      │    Version: 1.2.0 Codename: Ruby
│  |__   __|                              | |     │    MCPE: v1.1.0.55 Protocol: 113
│     | | ___  ___ ___  ___ _ __ __ _  ___| |_    │    IP:  Port: 19132
│     | |/ _ \/ __/ __|/ _ \ '__/ _` |/ __| __|   │    Query: 0.0.0.0
│     | |  __/\__ \__ \  __/ | | (_| | (__| |_    │    SSL Extension: true
│     |_|\___||___/___/\___|_|  \__,_|\___|\__|   │    Authentication: online mode/secure
│                                                 │  ------------------------------------------
│                                                 │    API Version: 3.0.1
│   Support: github.com/TesseractTeam/Tesseract   │    Language: eng
│					           │    Package: phar
└─────────────────────────────────────────────────┘  ------------------------------------------
Tesseract > Everything seems to be alright! Server started!
Tesseract > Loading recipes...
Tesseract > Loading StaffChat v1.1.1
Tesseract > Loading PerWorldChat v0.2.1
Tesseract > Preparing level "world"
[PE Server] Server was stopped.

I already removed the plugins,
I already changed the .phar and it continues to crash

**Comment by PetteriM1** [comment] 2017-07-04 20:35
This app can run **Genisys or Nukkit**, not Tesseract.

**Comment by fengberd** [comment] 2017-07-04 23:07
Tesseract always crash,I don't know why...Maybe it's author know.
GenisysPro and Nukkit works fine...

**Comment by nnnlog** [comment] 2017-07-05 04:42
@PetteriM1 PMMP

**Comment by Johnmacrocraft** [comment] 2017-07-05 08:29
@PetteriM1 You didn't think Tesseract is also part of PocketMine-MP software?
@DaviPatrick Tesseract is pretty messy spoon, it's developed by noob users (not at all), and they changed its structure so some plugins like Slapper don't work.

**Comment by fengberd** [comment] 2017-07-06 14:04
Agree,I suggest you to use GenisysPro,tessert never start successfully on
my device...
PMMP was dropped 32bit support,so I can't use it :/


Best Regards,
FENGberd

**Comment by Johnmacrocraft** [comment] 2017-07-08 07:50
@fengberd Do you know how to fix that _**[PE Server] Server was closed.**_ message only gets shown to console instead of starting server? I really hate this issue.

**Comment by SuperAdam47** [comment] 2017-07-26 08:00
@fengberd fix pls 
![screenshot_20170726-105546](https://user-images.githubusercontent.com/16169771/28610606-87e8a9d0-71f1-11e7-8edf-eec1ba08e724.png)
AND
![screenshot_20170726-105734](https://user-images.githubusercontent.com/16169771/28610613-9239f27c-71f1-11e7-8987-7e647d1ef924.png)

**Comment by PetteriM1** [comment] 2017-07-26 08:14
In first picture problem seems to be corrupted language file and in second picture it is maybe problem with world.

**Comment by SuperAdam47** [comment] 2017-07-26 08:20
@PetteriM1 The second photo is not the world's fault. My experiment on the normal world gave the same error

**Comment by Johnmacrocraft** [comment] 2017-07-26 12:40
@PetteriM1 The first one isn't related to language.

**Comment by Johnmacrocraft** [comment] 2017-07-27 09:48
@PetteriM1 Well, you deleted the comment...

**Comment by Johnmacrocraft** [comment] 2017-07-27 09:51
@DaviPatrick Wait... How did you get PHP7 binary with OpenSSL for Android working. In my case, the console always returned me message _**[PE Server] Server was stopped.**_.

**Comment by fengberd** [comment] 2017-07-29 05:42
Use old PHP binary please,it's caused by the binary


Best Regards,
FENGberd

**Comment by Johnmacrocraft** [comment] 2017-07-29 05:45
@fengberd So yeah, I was using old binary because of this. Is this actually supposed to happen on all phones or that PHP binary is incompatible with mine?

**Comment by fengberd** [comment] 2017-07-29 05:46
All phones I think,sometimes it happen on my phone but not all time...
(PS:Tesseract 100% crash and GenisysPro sometimes work fine.


Best Regards,
FENGberd

**Comment by Johnmacrocraft** [comment] 2017-07-29 05:47
@fengberd Oh, ok. Anyway I think this issue can also be closed as the person who reported this issue got an answer (Use other core).

**Comment by nnnlog** [comment] 2017-07-29 05:48
@fengberd Drop support Tesseract in MinecraftPEServer. In addititon, Tesseract is dead.

**Comment by AnUnknownPerson** [comment] 2017-08-23 21:18
Use https://github.com/SpigotPE-Team/SpigotPE we have MOB AI and 32 bit support

**Comment by nnnlog** [comment] 2017-08-23 21:28
@Fabiansigala wow

**Comment by AnUnknownPerson** [comment] 2017-08-23 21:39
Yes

**Closed as completed** 2017-09-03 09:45 UTC
